# .streamlit/secrets.toml or secrets.toml in the root app directory
# Replace these placeholders with your actual desired username and password
correct_username = "CC"
correct_password = "CC"

# Add your email secrets here too if not already present
# Replace these placeholders with your actual email configuration
email_sender = "YOUR_SENDER_EMAIL@example.com"
email_password = "YOUR_EMAIL_APP_PASSWORD" # Use an App Password if using Gmail/2FA
email_recipient = "YOUR_RECIPIENT_EMAIL@example.com"